[versions]
agp = "8.13.1"
kotlin-android = "2.2.21"
kotlin-android-coroutines = "1.10.2"
core-ktx = "1.17.0"
lifecycle-runtime-ktx = "2.10.0"
appcompat = "1.7.1"
activity = "1.11.0"
material = "1.13.0"
constraintlayout = "2.2.1"
work = "2.11.0"

[libraries]
kotlin-android-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlin-android-coroutines" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
work = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }

[bundles]
